### ISSUE TITLE
[Bug]: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by ItaloSa** [ifood/ifood-docusaurus-theme#18]
### Current Behavior

We're having an `Each child in a list should have a unique "key" prop` warning when using the theme in a project. Here are the warnings:

![image](https://user-images.githubusercontent.com/28374391/167702206-2a314500-cfe2-4546-8f73-391a9420c85d.png)

![image](https://user-images.githubusercontent.com/28374391/167702561-3990d9bb-9eb2-4b9c-8422-82f1d8dddf2e.png)

### Expected Behavior

Avoid those warnings to happen.

### Steps to reproduce

Install the theme in a new compatible project, then start the development server.

**Comment by eliezer-souza** [comment]
Developing!
